# SPDX-License-Identifier: GPL-2.0
TARGET ?= $(shell basename $(shell pwd))_test
CFLAGS += -O2
OBJS := main_test.o
OBJS += isort1.o isort1_test.o
OBJS += isort2.o isort2_test.o
OBJS += isort3.o isort3_test.o
include ../lib.mk
