# SPDX-License-Identifier: GPL-2.0
TARGET ?= $(shell basename $(shell pwd))_test
OBJS := main_test.o
OBJS += find_first.o find_first_test.o
OBJS += find_first1000.o find_first1000_test.o
include ../lib.mk
